# Generated by Django 4.1.3 on 2022-11-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0003_rename_name_categoryclinics_categoryname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="DoctorPrice",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="DoctorService",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="DoctorWork_time",
        ),
        migrations.AddField(
            model_name="doctor",
            name="DoctorContent",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="ServiceClinic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Catalog.clinics",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="ServicePrice",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="clinics",
            name="ClinicPhoto",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="services",
            name="ServiceContent",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="services",
            name="ServicePhoto",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/"),
        ),
    ]
