# Generated by Django 4.1.3 on 2022-12-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0004_remove_doctor_doctorprice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinics",
            name="ClinicCity",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="DoctorExperience",
        ),
        migrations.RemoveField(
            model_name="services",
            name="ServiceContent",
        ),
    ]
