# Generated by Django 4.1.3 on 2023-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0007_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
